### ISSUE TITLE
Using Java Future is limiting ability to easily scale in environments like Scala Akka

### ISSUE THREAD

**Issue by denisbetsi** [crate/crate-jdbc#107]
As I am attempting to build out a micro service, I am running into issue of using current Java client response which returns Future<SQLResponse>  turns out that Future response is not really all that Future friendly.

CompletableFuture on the other hand is the way to go. Unlike Future there's a way to get a call back when the call is complete vs having to either Await (block) the thread or while loop while waiting for isDone() to become true which might as well be blocking.

Are there any plans to transition the client into fluent asynchronous processing vs old school Future type?

**Comment by mfussenegger** [comment]
CompletableFuture is Java 8 only and Crate is still running on Java 7 (although we're phasing that out).

The CrateClient also has a second overload were you can pass a ActionListener which is callback based. Can you use that instead? I think it should be possible to create some kind of wrapper class if you really want to turn that into a CompletableFuture.

There are no immediate plans to transition the client, but I can see that it could be helpful.


Btw. this repo is for the JDBC driver. The CrateClient itself is part of the https://github.com/crate/crate repo. (I was confused for a moment because I didn't quite understand which Future you're referring too).

**Comment by denisbetsi** [comment]
Jodok asked me to create 2 issues under crate-jdbc so I followed his guidelines. I'll use the ActionListener in the interim, it has the callback I was looking for :)
