### ISSUE TITLE
 unmappable character (0x9D) for encoding windows-1252 System.out.println(ΓÇ£Else PartΓÇ?);

### ISSUE THREAD

**Issue by abdulsaede** [crate/crate-jdbc#325]

**Comment by abdulsaede** [comment]
what is the problem please explain

**Comment by autophagy** [comment]
Hi @abdulsaede - it seems that this is an encoding error. I think it's because you might have used the `“` and `”` characters which aren't valid for the encoding you have chosen, instead of the `"` character. 

Instead of:
```
System.out.println(“Else Part”);
```
Try:
```
System.out.println("Else Part");
```

or try setting the encoding you're using to something that supports the characters you'd like to use, like UTF-8. This Stack Overflow question might be helpful in that regard: https://stackoverflow.com/questions/464874/unmappable-character-for-encoding-warning-in-java
