### ISSUE TITLE
Investigate differences between this driver and canonical PostgreSQL JDBC driver

### ISSUE THREAD

**Issue by amotl** [crate/crate-jdbc#353]
Hi.

This picks up a note from #347:

> Currently, we still need this fork of the JDBC driver, as recently experienced with interoperability tests on [Apache Kafka, Apache Flink and CrateDB](https://github.com/crate/cratedb-examples/tree/0.1.0/spikes/kafka-flink) [^1]. Regarding this, I will have to refresh my memory about this in order to describe my observations with the vanilla PostgreSQL JDBC driver.

With kind regards,
Andreas.

[^1]: See also https://github.com/crate/cratedb-flink-jobs/issues/3

**Comment by amotl** [comment]
I think with GH-365 and https://github.com/crate/pgjdbc/pull/43, we can consider this as resolved reasonably. At least, we've clarified that we need the driver, and under which circumstances. What do you think, @matriv?

**Comment by matriv** [comment]
Yesterday at `Community Day #2` Event, a 4.8.x CrateDB user mentioned that they need this as the vanilla postgresql driver issues some queries/statements that fail since this older version is probably missing some pg compatibility that has been added since to CrateDB.

So,I think it's fine not to continue investigating more.
